/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(goertzel_scopy_fc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(833cda2246d3ad31aa02e96d8f5171fd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/scopy/goertzel_scopy_fc.h>
// pydoc.h is automatically generated in the build directory
#include <goertzel_scopy_fc_pydoc.h>

void bind_goertzel_scopy_fc(py::module& m)
{

    using goertzel_scopy_fc    = gr::scopy::goertzel_scopy_fc;


    py::class_<goertzel_scopy_fc, gr::sync_decimator,
        std::shared_ptr<goertzel_scopy_fc>>(m, "goertzel_scopy_fc", D(goertzel_scopy_fc))

        .def(py::init(&goertzel_scopy_fc::make),
           D(goertzel_scopy_fc,make)
        )
        



        ;




}








