/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(modulo_const_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b2e849da2a86024ea726cbd57bc35225)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/scopy/modulo_const_ff.h>
// pydoc.h is automatically generated in the build directory
#include <modulo_const_ff_pydoc.h>

void bind_modulo_const_ff(py::module& m)
{

    using modulo_const_ff    = gr::scopy::modulo_const_ff;


    py::class_<modulo_const_ff, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<modulo_const_ff>>(m, "modulo_const_ff", D(modulo_const_ff))

        .def(py::init(&modulo_const_ff::make),
           D(modulo_const_ff,make)
        )
        



        ;




}








