/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(t_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bd72b8605cd27f5a31fe1001d39bb4a2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/scopy/t_source.h>
// pydoc.h is automatically generated in the build directory
#include <t_source_pydoc.h>

void bind_t_source(py::module& m)
{

    using t_source    = gr::scopy::t_source;


    py::class_<t_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<t_source>>(m, "t_source", D(t_source))

        .def(py::init(&t_source::make),
           D(t_source,make)
        )
        



        ;




}








